apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: demo-issuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    #server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: demo-issuer-account-key
    solvers:
    - http01:
        ingress:
          ingressClassName: openshift-default
